// Golden vector generator — implementation plan Phase 3.
//
// RUN ONCE. Its output, native/test/golden/vectors.bin, is FROZEN: it is the
// contract C-01/C-02 compare devices against (contract §2.2). After it is
// committed, a mismatch is an encoder regression — never a reason to run this
// again.
//
//   itantra-golden-generate <output.bin> [--format-version-bump]
//
// Refuses to overwrite an existing file. --format-version-bump exists only for
// a deliberate packet-format or coder version bump, recorded in the packet
// spec change log (contract §7.2). Adding vectors for later phases (real Tier
// 1 / Tier 2 tables) is also a deliberate, recorded act, and must keep every
// existing vector byte-identical.
//
// Every vector is generated by assemble() and checked by parse() before the
// file is written, so a broken encoder cannot freeze a payload it cannot read.
//
// Inputs are pre-encryption (packet §6.10.1). The byte-symbol vectors stand in
// for literals and byte fallback: the Tier 2 subword vocabulary and the Tier 1
// tables do not exist until Phases 7 and 8, so here the symbols are the UTF-8
// bytes themselves, coded under a 256-symbol table with a non-zero floor.

#include "common/hash.h"
#include "golden/golden_format.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <initializer_list>
#include <memory>
#include <string>
#include <vector>

using namespace itantra;

namespace {

struct XorShift32 {
    u32 s;
    u32 next() {
        s ^= s << 13;
        s ^= s >> 17;
        s ^= s << 5;
        return s;
    }
    u32 below(u32 n) { return n == 0u ? 0u : next() % n; }
};

std::vector<Symbol> utf8(std::initializer_list<u32> codepoints) {
    std::vector<Symbol> out;
    for (u32 cp : codepoints) {
        if (cp < 0x80u) {
            out.push_back(cp);
        } else if (cp < 0x800u) {
            out.push_back(0xC0u | (cp >> 6));
            out.push_back(0x80u | (cp & 0x3Fu));
        } else if (cp < 0x10000u) {
            out.push_back(0xE0u | (cp >> 12));
            out.push_back(0x80u | ((cp >> 6) & 0x3Fu));
            out.push_back(0x80u | (cp & 0x3Fu));
        } else {
            out.push_back(0xF0u | (cp >> 18));
            out.push_back(0x80u | ((cp >> 12) & 0x3Fu));
            out.push_back(0x80u | ((cp >> 6) & 0x3Fu));
            out.push_back(0x80u | (cp & 0x3Fu));
        }
    }
    return out;
}

std::vector<Symbol> ascii(const char* s) {
    std::vector<Symbol> out;
    for (; *s != '\0'; ++s) out.push_back(static_cast<u8>(*s));
    return out;
}

std::vector<Symbol> cat(std::vector<Symbol> a, const std::vector<Symbol>& b) {
    a.insert(a.end(), b.begin(), b.end());
    return a;
}

std::vector<u32> zipf(u32 n, u32 scale) {
    std::vector<u32> f(n);
    for (u32 i = 0u; i < n; ++i) f[i] = 1u + scale / (i + 1u);
    return f;
}

// A byte table shaped like trained text: Latin letters, space, UTF-8 lead and
// continuation bytes common, every other byte at the floor of 1 (tier §6.3).
std::vector<u32> trained_bytes() {
    std::vector<u32> f(256u, 1u);
    for (u32 c = 'a'; c <= 'z'; ++c) f[c] = 400u;
    for (u32 c = 'A'; c <= 'Z'; ++c) f[c] = 60u;
    for (u32 c = '0'; c <= '9'; ++c) f[c] = 80u;
    f[' '] = 600u;
    f[','] = 40u;
    f['.'] = 40u;
    for (u32 b = 0x80u; b <= 0xBFu; ++b) f[b] = 250u;
    for (u32 b = 0xC2u; b <= 0xDFu; ++b) f[b] = 20u;
    for (u32 b = 0xE0u; b <= 0xEFu; ++b) f[b] = 300u;
    for (u32 b = 0xF0u; b <= 0xF4u; ++b) f[b] = 5u;
    return f;
}

std::vector<u32> sparse_table() {
    std::vector<u32> f(300u);
    for (u32 i = 0u; i < 300u; ++i) f[i] = (i % 3u == 0u) ? 0u : 1u + (i * 37u) % 97u;
    return f;
}

struct Spec {
    std::string         name;
    Tier                tier         = Tier::Tier1;
    u8                  seq          = 0u;
    bool                hash_present = false;
    u16                 context_hash = 0u;
    Priority            priority     = Priority::Normal;
    bool                negation     = false;
    LangId              language     = 0u;
    u8                  mode         = golden::kScheduleCyclic;
    std::vector<u16>    schedule;
    std::vector<Symbol> symbols;
};

class Builder {
public:
    golden::GoldenFile file;

    u16 model(const std::vector<u32>& frequencies) {
        golden::GoldenModel m;
        m.frequencies = frequencies;
        if (!m.table.assign(m.frequencies.data(), static_cast<u32>(m.frequencies.size()))) {
            std::fprintf(stderr, "generator bug: invalid table %zu\n", file.models.size());
            std::exit(3);
        }
        file.models.push_back(std::move(m));
        return static_cast<u16>(file.models.size() - 1u);
    }

    void add(const Spec& s) {
        golden::GoldenVector v;
        v.name                  = s.name;
        v.metadata.tier         = s.tier;
        v.metadata.symbol_count = static_cast<u16>(s.symbols.size());
        v.metadata.seq          = s.seq;
        v.metadata.hash_present = s.hash_present;
        v.metadata.context_hash = s.context_hash;
        v.metadata.priority     = s.priority;
        v.metadata.negation     = s.negation;
        v.metadata.language     = s.language;
        v.schedule_mode         = s.mode;
        v.schedule              = s.schedule;
        v.symbols               = s.symbols;
        file.vectors.push_back(std::move(v));
    }

    const StaticModel& table_at(u8 mode, const std::vector<u16>& schedule, u32 i) const {
        const std::size_t n = schedule.size();
        const std::size_t k = mode == golden::kScheduleCyclic ? i % n : (i < n ? i : n - 1u);
        return file.models[schedule[k]].table;
    }

    // Symbols drawn by probability, as real payloads are.
    std::vector<Symbol> weighted(XorShift32& rng, u8 mode, const std::vector<u16>& schedule, u32 count) const {
        std::vector<Symbol> out(count);
        for (u32 i = 0u; i < count; ++i) {
            const StaticModel& t = table_at(mode, schedule, i);
            SymbolRange r{0u, 0u, 0u};
            out[i] = t.find(rng.below(t.total()), r);
        }
        return out;
    }
};

const char* priority_name(u32 p) {
    return p == 0u ? "normal" : "critical";
}

void build(Builder& b) {
    XorShift32 rng{0x60D1E5EDu};

    const u16 binary     = b.model({1u, 1u});
    const u16 certain    = b.model({1u});
    const u16 flat_bytes = b.model(std::vector<u32>(256u, 1u));
    const u16 bytes      = b.model(trained_bytes());
    const u16 intent     = b.model(zipf(64u, 4096u));
    const u16 slot_mode  = b.model({60u, 10u, 25u, 5u});
    const u16 slot_value = b.model(zipf(4096u, 65536u));
    const u16 extreme    = b.model({1u, kModelMaxTotal - 2u, 1u});
    const u16 follow     = b.model({1u, 2u, 1u});
    const u16 wide       = b.model(std::vector<u32>(8192u, 2048u));   // total exactly 2^24
    const u16 sparse     = b.model(sparse_table());

    const std::vector<u16> t1_shape = {intent, slot_mode, slot_value, slot_mode, slot_value};
    const std::vector<Symbol> t1_frame = {3u, 2u, 312u, 0u, 47u};
    const u16 zero_table_hash = wire_context_hash(context_hash(ContextHashInput{}));   // 0xF8A

    auto spec = [](const std::string& name, Tier tier) {
        Spec s;
        s.name = name;
        s.tier = tier;
        return s;
    };

    // --- minimum: 1 symbol, no hash, both tiers -----------------------------
    {
        Spec s = spec("min-t1-1sym-nohash", Tier::Tier1);
        s.schedule = t1_shape;
        s.symbols = {3u};
        b.add(s);
    }
    {
        Spec s = spec("min-t2-1sym-nohash", Tier::Tier2);
        s.schedule = {bytes};
        s.symbols = ascii("a");
        b.add(s);
    }

    // --- all variants: tier × hash_present × priority × negation ------------
    u32 k = 0u;
    for (u32 hp = 0u; hp < 2u; ++hp) {
        for (u32 pri = 0u; pri < 2u; ++pri) {
            for (u32 neg = 0u; neg < 2u; ++neg, ++k) {
                Spec s = spec("variant-t1-hash" + std::to_string(hp) + "-" + priority_name(pri) +
                                  "-neg" + std::to_string(neg),
                              Tier::Tier1);
                s.seq = static_cast<u8>(17u + 29u * k);
                s.hash_present = hp != 0u;
                s.context_hash = hp != 0u ? static_cast<u16>((0x5A5u + 0x111u * k) & 0xFFFu) : 0u;
                s.priority = static_cast<Priority>(pri);
                s.negation = neg != 0u;
                s.schedule = t1_shape;
                s.symbols = t1_frame;
                b.add(s);
            }
        }
    }
    k = 0u;
    for (u32 hp = 0u; hp < 2u; ++hp) {
        for (u32 pri = 0u; pri < 2u; ++pri, ++k) {
            Spec s = spec("variant-t2-hash" + std::to_string(hp) + "-" + priority_name(pri), Tier::Tier2);
            s.seq = static_cast<u8>(200u + 13u * k);
            s.hash_present = hp != 0u;
            s.context_hash = hp != 0u ? zero_table_hash : 0u;
            s.priority = static_cast<Priority>(pri);
            s.language = static_cast<LangId>(1u + 4u * k);
            s.schedule = {bytes};
            s.symbols = ascii("fire at north gate");
            b.add(s);
        }
    }

    // --- symbol_count at the escape boundary, and the maximum ---------------
    const u32 boundary_counts[] = {30u, 31u, 32u};
    for (u32 count : boundary_counts) {
        Spec s1 = spec("count-" + std::to_string(count) + "-t1-hash", Tier::Tier1);
        s1.seq = static_cast<u8>(count);
        s1.hash_present = true;
        s1.context_hash = zero_table_hash;
        s1.schedule = t1_shape;
        s1.symbols = b.weighted(rng, golden::kScheduleCyclic, t1_shape, count);
        b.add(s1);

        Spec s2 = spec("count-" + std::to_string(count) + "-t2-hash", Tier::Tier2);
        s2.seq = static_cast<u8>(count + 100u);
        s2.hash_present = true;
        s2.context_hash = 0x3C3u;
        s2.language = 2u;
        s2.schedule = {bytes};
        s2.symbols = b.weighted(rng, golden::kScheduleCyclic, s2.schedule, count);
        b.add(s2);
    }
    {
        Spec s = spec("count-max-t1-hash", Tier::Tier1);
        s.seq = 77u;
        s.hash_present = true;
        s.context_hash = 0xFFFu;
        s.priority = Priority::Critical;
        s.negation = true;
        s.schedule = t1_shape;
        s.symbols = b.weighted(rng, golden::kScheduleCyclic, t1_shape, kMaxSymbolCount);
        b.add(s);
    }
    {
        Spec s = spec("count-max-t2-hash-trained-bytes", Tier::Tier2);
        s.seq = 78u;
        s.hash_present = true;
        s.context_hash = 0x001u;
        s.language = 3u;
        s.schedule = {bytes};
        s.symbols = b.weighted(rng, golden::kScheduleCyclic, s.schedule, kMaxSymbolCount);
        b.add(s);
    }
    {
        Spec s = spec("count-max-t2-hash-certain-symbol", Tier::Tier2);
        s.seq = 79u;
        s.hash_present = true;
        s.context_hash = 0x800u;
        s.schedule = {certain};
        s.symbols = std::vector<Symbol>(kMaxSymbolCount, 0u);
        b.add(s);
    }
    {
        Spec s = spec("count-max-t2-hash-worst-case-size", Tier::Tier2);
        s.seq = 80u;
        s.hash_present = true;
        s.context_hash = 0xFFFu;
        s.priority = Priority::Critical;
        s.language = 15u;
        s.schedule = {extreme};
        s.symbols = std::vector<Symbol>(kMaxSymbolCount, 0u);
        b.add(s);
    }

    // --- field extremes ------------------------------------------------------
    {
        Spec s = spec("field-seq-255-hash-000-t1", Tier::Tier1);
        s.seq = 255u;
        s.hash_present = true;
        s.context_hash = 0x000u;
        s.schedule = t1_shape;
        s.symbols = t1_frame;
        b.add(s);
    }
    {
        Spec s = spec("field-seq-128-t2", Tier::Tier2);
        s.seq = 128u;
        s.schedule = {bytes};
        s.symbols = ascii("send help");
        b.add(s);
    }
    {
        Spec s = spec("field-hash-fff-t1-critical-negated", Tier::Tier1);
        s.seq = 1u;
        s.hash_present = true;
        s.context_hash = 0xFFFu;
        s.priority = Priority::Critical;
        s.negation = true;
        s.schedule = t1_shape;
        s.symbols = t1_frame;
        b.add(s);
    }
    {
        Spec s = spec("field-hash-000-t2", Tier::Tier2);
        s.seq = 2u;
        s.hash_present = true;
        s.context_hash = 0x000u;
        s.schedule = {bytes};
        s.symbols = ascii("casualties at south gate");
        b.add(s);
    }
    {
        Spec s = spec("field-language-15-t2", Tier::Tier2);
        s.seq = 3u;
        s.language = 15u;
        s.schedule = {bytes};
        s.symbols = ascii("oxygen");
        b.add(s);
    }
    {
        Spec s = spec("empty-t2-nohash", Tier::Tier2);
        s.schedule = {bytes};
        b.add(s);
    }
    {
        Spec s = spec("empty-t2-hash-critical", Tier::Tier2);
        s.seq = 4u;
        s.hash_present = true;
        s.context_hash = zero_table_hash;
        s.priority = Priority::Critical;
        s.schedule = {bytes};
        b.add(s);
    }

    // --- literals in every script, including byte fallback -------------------
    struct Literal {
        const char*         name;
        std::vector<Symbol> text;
    };
    const Literal literals[] = {
        {"literal-devanagari-hindi", utf8({0x0909u, 0x0924u, 0x094Du, 0x0924u, 0x0930u, 0x20u, 0x0926u, 0x094Du,
                                           0x0935u, 0x093Eu, 0x0930u, 0x20u, 0x092Au, 0x0930u, 0x20u, 0x0906u, 0x0917u})},
        {"literal-devanagari-marathi", utf8({0x0909u, 0x0924u, 0x094Du, 0x0924u, 0x0930u, 0x20u, 0x0926u, 0x0930u,
                                             0x0935u, 0x093Eu, 0x091Cu, 0x093Eu, 0x20u, 0x091Cu, 0x0935u, 0x0933u,
                                             0x20u, 0x0906u, 0x0917u})},
        {"literal-gujarati", utf8({0x0A89u, 0x0AA4u, 0x0ACDu, 0x0AA4u, 0x0AB0u, 0x20u, 0x0AA6u, 0x0AB0u, 0x0AB5u,
                                   0x0ABEu, 0x0A9Cu, 0x0ABEu, 0x20u, 0x0AAAu, 0x0ABEu, 0x0AB8u, 0x0AC7u, 0x20u,
                                   0x0A86u, 0x0A97u})},
        {"literal-kannada", utf8({0x0C89u, 0x0CA4u, 0x0CCDu, 0x0CA4u, 0x0CB0u, 0x20u, 0x0CA6u, 0x0CCDu, 0x0CB5u,
                                  0x0CBEu, 0x0CB0u, 0x0CA6u, 0x0CB2u, 0x0CCDu, 0x0CB2u, 0x0CBFu, 0x20u, 0x0CACu,
                                  0x0CC6u, 0x0C82u, 0x0C95u, 0x0CBFu})},
        {"literal-malayalam", utf8({0x0D35u, 0x0D1Fu, 0x0D15u, 0x0D4Du, 0x0D15u, 0x0D47u, 0x20u, 0x0D35u, 0x0D3Eu,
                                    0x0D24u, 0x0D3Fu, 0x0D32u, 0x0D3Fu, 0x0D7Du, 0x20u, 0x0D24u, 0x0D40u})},
        {"literal-tamil", utf8({0x0BB5u, 0x0B9Fu, 0x0B95u, 0x0BCDu, 0x0B95u, 0x0BC1u, 0x20u, 0x0BB5u, 0x0BBEu,
                                0x0B9Au, 0x0BB2u, 0x0BBFu, 0x0BB2u, 0x0BCDu, 0x20u, 0x0BA4u, 0x0BC0u})},
        {"literal-telugu", utf8({0x0C09u, 0x0C24u, 0x0C4Du, 0x0C24u, 0x0C30u, 0x20u, 0x0C26u, 0x0C4Du, 0x0C35u,
                                 0x0C3Eu, 0x0C30u, 0x0C02u, 0x20u, 0x0C35u, 0x0C26u, 0x0C4Du, 0x0C26u, 0x20u,
                                 0x0C2Eu, 0x0C02u, 0x0C1Fu})},
        {"literal-odia", utf8({0x0B09u, 0x0B24u, 0x0B4Du, 0x0B24u, 0x0B30u, 0x20u, 0x0B26u, 0x0B4Du, 0x0B71u,
                               0x0B3Eu, 0x0B30u, 0x0B30u, 0x0B47u, 0x20u, 0x0B28u, 0x0B3Fu, 0x0B06u, 0x0B01u})},
        {"literal-bengali", utf8({0x0989u, 0x09A4u, 0x09CDu, 0x09A4u, 0x09B0u, 0x20u, 0x09A6u, 0x09B0u, 0x099Cu,
                                  0x09BEu, 0x09DFu, 0x20u, 0x0986u, 0x0997u, 0x09C1u, 0x09A8u})},
        {"literal-latin-english", ascii("fire at north gate, send help immediately")},
        {"literal-native-digits", utf8({0x0969u, 0x20u, 0x0BE9u, 0x20u, 0x09E9u, 0x20u, 0x33u})},
        {"literal-code-mixed-tamil-english",
         cat(cat(ascii("north gate "), utf8({0x0BB2u, 0x20u, 0x0BA4u, 0x0BC0u, 0x2Cu, 0x20u})),
             cat(ascii("ambulance "), utf8({0x0B85u, 0x0BA9u, 0x0BC1u, 0x0BAAu, 0x0BCDu, 0x0BAAu, 0x0BC1u,
                                            0x0B99u, 0x0BCDu, 0x0B95u})))},
        {"literal-byte-fallback-latin-extended", utf8({0x1E8Du})},   // tier §6.2 example: E1 BA 8D
        {"literal-byte-fallback-emoji", utf8({0x1F691u, 0x1F525u})},
        {"literal-byte-fallback-cjk-arabic", utf8({0x706Bu, 0x20u, 0x0646u, 0x0627u, 0x0631u})},
        {"literal-nfc-precomposed", utf8({0x0958u, 0x20u, 0x00E9u})},
        {"literal-nfd-decomposed", utf8({0x0915u, 0x093Cu, 0x20u, 0x0065u, 0x0301u})},
    };
    k = 0u;
    for (const Literal& lit : literals) {
        Spec s = spec(lit.name, Tier::Tier2);
        s.seq = static_cast<u8>(10u + k++);
        s.schedule = {bytes};
        s.symbols = lit.text;
        b.add(s);
    }
    {
        Spec s = spec("literal-flat-byte-table-devanagari", Tier::Tier2);
        s.seq = 40u;
        s.schedule = {flat_bytes};
        s.symbols = literals[0].text;
        b.add(s);
    }
    {
        // Tier 1 shape: intent, slot mode, then a literal's bytes (tier §5.7).
        Spec s = spec("literal-in-tier1-frame-tamil", Tier::Tier1);
        s.seq = 41u;
        s.mode = golden::kScheduleLastRepeats;
        s.schedule = {intent, slot_mode, bytes};
        s.symbols = cat({5u, 3u}, literals[5].text);
        b.add(s);
    }

    // --- adversarial ---------------------------------------------------------
    {
        std::vector<Symbol> all(256u);
        for (u32 i = 0u; i < 256u; ++i) all[i] = i;

        Spec s = spec("adversarial-all-256-bytes-flat-table", Tier::Tier2);
        s.seq = 50u;
        s.schedule = {flat_bytes};
        s.symbols = all;
        b.add(s);

        Spec t = spec("adversarial-all-256-bytes-trained-table", Tier::Tier2);
        t.seq = 51u;
        t.hash_present = true;
        t.context_hash = 0x7E7u;
        t.schedule = {bytes};
        t.symbols = all;
        b.add(t);
    }
    {
        Spec s = spec("adversarial-random-bytes", Tier::Tier2);
        s.seq = 52u;
        s.schedule = {bytes};
        for (u32 i = 0u; i < 300u; ++i) s.symbols.push_back(rng.next() & 0xFFu);
        b.add(s);
    }
    {
        Spec s = spec("adversarial-min-probability-run", Tier::Tier1);
        s.seq = 53u;
        s.priority = Priority::Critical;
        s.negation = true;
        s.schedule = {extreme};
        s.symbols = std::vector<Symbol>(64u, 2u);
        b.add(s);
    }
    {
        Spec s = spec("adversarial-follow-bit-run", Tier::Tier2);
        s.seq = 54u;
        s.hash_present = true;
        s.context_hash = 0xA5Au;
        s.schedule = {follow};
        s.symbols = std::vector<Symbol>(1500u, 1u);
        b.add(s);
    }
    {
        Spec s = spec("adversarial-binary-alternating", Tier::Tier1);
        s.seq = 55u;
        s.schedule = {binary};
        for (u32 i = 0u; i < 400u; ++i) s.symbols.push_back(i & 1u);
        b.add(s);
    }
    {
        Spec s = spec("adversarial-wide-alphabet", Tier::Tier2);
        s.seq = 56u;
        s.schedule = {wide};
        for (u32 i = 0u; i < 200u; ++i) s.symbols.push_back(rng.below(8192u));
        b.add(s);
    }
    {
        Spec s = spec("adversarial-sparse-table", Tier::Tier1);
        s.seq = 57u;
        s.schedule = {sparse};
        s.symbols = b.weighted(rng, golden::kScheduleCyclic, s.schedule, 150u);
        b.add(s);
    }
    {
        Spec s = spec("adversarial-mixed-extremes", Tier::Tier2);
        s.seq = 58u;
        s.hash_present = true;
        s.context_hash = 0x5A5u;
        s.schedule = {extreme, follow, certain, flat_bytes};
        const u32 alphabets[] = {3u, 3u, 1u, 256u};
        for (u32 i = 0u; i < 600u; ++i) s.symbols.push_back(rng.below(alphabets[i % 4u]));
        b.add(s);
    }
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2 || argc > 3 || (argc == 3 && std::strcmp(argv[2], "--format-version-bump") != 0)) {
        std::fprintf(stderr, "usage: itantra-golden-generate <output.bin> [--format-version-bump]\n");
        return 2;
    }
    const char* path = argv[1];
    if (golden::file_exists(path) && argc != 3) {
        std::fprintf(stderr,
                     "REFUSED: %s exists. Golden vectors are frozen (contract §2.2, §7.2).\n"
                     "A mismatch is an encoder regression. Regenerate only for a deliberate format\n"
                     "version bump recorded in the packet spec change log (--format-version-bump).\n",
                     path);
        return 1;
    }

    Builder b;
    build(b);

    auto payload = std::make_unique<NativePayload>();
    auto parsed  = std::make_unique<ParsedPayload>();
    for (golden::GoldenVector& v : b.file.vectors) {
        const golden::ScheduledModel model(b.file.models, v);
        const AssemblyInput in = golden::input_of(v, model);
        const AsmResult r = assemble(in, *payload);
        if (r != AsmResult::Ok) {
            std::fprintf(stderr, "generator: assemble failed for %s (%u)\n", v.name.c_str(), static_cast<u32>(r));
            return 3;
        }
        v.payload.assign(payload->bytes, payload->bytes + payload->len);
        v.metadata_bits = payload->metadata_bits;

        const golden::FixedSelector selector(&model);
        const ParseStatus ps = parse(v.payload.data(), static_cast<u32>(v.payload.size()), selector, *parsed);
        bool same = ps == ParseStatus::Ok && parsed->metadata == v.metadata &&
                    parsed->metadata_bits == v.metadata_bits;
        for (std::size_t i = 0u; same && i < v.symbols.size(); ++i) same = parsed->symbols[i] == v.symbols[i];
        if (!same) {
            std::fprintf(stderr, "generator: %s does not parse back to its input\n", v.name.c_str());
            return 3;
        }
    }

    const std::vector<u8> bytes = golden::serialize(b.file);
    golden::GoldenFile check;
    std::string error;
    if (!golden::deserialize(bytes, check, error) || check.vectors.size() != b.file.vectors.size()) {
        std::fprintf(stderr, "generator: serialised file does not load back: %s\n", error.c_str());
        return 3;
    }
    if (!golden::write_file(path, bytes)) {
        std::fprintf(stderr, "generator: cannot write %s\n", path);
        return 2;
    }

    std::printf("golden vectors: file v%u, packet format v%u, coder v%u, %zu tables, %zu vectors, %zu bytes, crc32 0x%08X\n",
                b.file.file_version, b.file.packet_format_version, b.file.coder_version, b.file.models.size(),
                b.file.vectors.size(), bytes.size(),
                golden::crc32(bytes.data(), bytes.size() - 4u));
    std::printf("%-44s tier count meta  len  first bytes\n", "vector");
    for (const golden::GoldenVector& v : b.file.vectors) {
        std::printf("%-44s  %u  %5zu  %3u %5zu ", v.name.c_str(), static_cast<u32>(v.metadata.tier),
                    v.symbols.size(), v.metadata_bits, v.payload.size());
        for (std::size_t i = 0u; i < v.payload.size() && i < 8u; ++i) std::printf(" %02X", v.payload[i]);
        std::printf("\n");
    }
    return 0;
}
